### ISSUE TITLE
Change search voice under the cursor

### ISSUE THREAD

**Issue by crivotz** [google/vim-searchindex#15]
It would be great if the search under the cursor was highlighted in a different color than the other.
First I used this script but rightly `n` and `N` are now handled by searchindex.

```
function! HLNext (blinktime)
  highlight RedOnRed ctermfg=red ctermbg=red
  let [bufnum, lnum, col, off] = getpos('.')
  let matchlen = strlen(matchstr(strpart(getline('.'),col-1),@/))
  echo matchlen
  let ring_pat = (lnum > 1 ? '\%'.(lnum-1).'l\%>'.max([col-4,1]) .'v\%<'.(col+matchlen+3).'v.\|' : '')
    \ . '\%'.lnum.'l\%>'.max([col-4,1]) .'v\%<'.col.'v.'
    \ . '\|'
    \ . '\%'.lnum.'l\%>'.max([col+matchlen-1,1]) .'v\%<'.(col+matchlen+3).'v.'
    \ . '\|'
    \ . '\%'.(lnum+1).'l\%>'.max([col-4,1]) .'v\%<'.(col+matchlen+3).'v.'
  let ring = matchadd('RedOnRed', ring_pat, 101)
  redraw
  exec 'sleep ' . float2nr(a:blinktime * 1000) . 'm'
  call matchdelete(ring)
  redraw
endfunction

```
Maybe not all this stuff, different color is enough

**Comment by dbarnett** [comment]
You could define mappings yourself that chain the searchindex operations with your own since it defines `<Plug>` mappings that are easy to customize. Example:
```vim
nmap <silent> n n<Plug>SearchIndex:call HLNext(1)<CR>
```
Custom highlight color/style is independent functionality that you might want with or without searchindex so I'd suggest customizing it outside searchindex. If there were a well-known plugin that handled search highlighting, it might be reasonable for searchindex to detect and cooperate with that plugin on the mappings, though.

@rburny How about updating searchindex's help files to explain how to customize the mappings?

**Comment by crivotz** [comment]
Cool so can I try to integrate it with [vim-interestingwords](https://github.com/lfv89/vim-interestingwords)
Thanks @dbarnett
