### ISSUE TITLE
Side effects of `s:MatchesInRange()`

### ISSUE THREAD

**Issue by lacygoill** [google/vim-searchindex#18]
Inside the function `s:MatchesInRange()`, this command is executed:

     silent! execute a:range . 's///en' . gflag

I think it has several undesired effects, some of which could be mitigated.

It adds an entry in the jumplist: this could be solved with `:keepjumps`:

         silent! execute 'keepjumps '.a:range . 's///en' . gflag

It alters the `[` and `]` marks: this could be solved by saving/restoring the marks:

    let marks_save = [ getpos("'["), getpos("']") ]
    ...
    silent! execute a:range . 's///en' . gflag
    ...
    call setpos("'[", marks_save[0])
    call setpos("']", marks_save[1])

It makes you lose  some metacharacters and flags like `~` and `&` (see `:h :&` and `:h :~`).
For this issue, I have no idea how to fix it. I've tried to think about mechanisms to save and restore them, but they are not reliable.

You would need to find a way to execute the substitution without Vim logging anything, but I don't know if it's possible.

**Comment by dbarnett** [comment]
I would guess an implementation based on `search()` rather than a `:substitute` command would have a lot fewer side-effects, if we're not stuck w/ this approach for performance reasons or something. @rburny have we already looked into using `search()`?

**Comment by lacygoill** [comment]
@dbarnett Yes, initially I had the same idea as you. A `while` loop invoking `search()` which increments a counter (with a guard to avoid being stuck in an infinite one). Unfortunately, in my limited testing, it seemed that `:substitute` was sometimes much faster than `search()`. Maybe I made a mistake, or maybe I just had bad luck with some particular patterns though.

But if `search()` can, indeed, be much slower than `:substitute`, I prefer using the latter, because I value the speed of the plugin more than the lost flags/metacharacters, as I almost never use them.

Also, there are a few [workarounds](https://stackoverflow.com/a/45346599/8243465) to the possible slowness of `search()`, including the `4`th optional argument `{timeout}`.

**Comment by dbarnett** [comment]
Alright cool, sounds like you've investigated in way more depth than I have. =)
So it sounds like the best path forward is to add the two improvements you mentioned along with some comments about why `search()` isn't an option for the benefit of anyone trying to improve it in the future.

**Comment by rburny** [comment]
Thanks for investigating these!

Indeed, I have used `:s` command because it is much faster. In contrast, any solution that implements a loop in Vimscript (like `search()` loop) tends to be slow, especially on large files.

I agree with your assessment - let's fix what we can within the current solution. Pull requests are welcome :)

**Comment by liushapku** [comment]
One side effect of `silent! execute a:range . 's///en' . gflag` is that it changes the last substitute string.

For example:

    :s/red/blue
    /green  (press enter here invokes <Plug>SearchIndex which sets the last substitute string to ''
    :~

Without the plugin, the last `:~` will replace `green` with `blue`. With the plugin, it will replace `green` with empty string. 

The case can be fixed by changing the above mentioned line to

    silent! execute a:range . 's//~/en' . gflag

A PR [#20](https://github.com/google/vim-searchindex/pull/20) is created for this.

**Comment by liushapku** [comment]
The side effect of changing the last used flags is not addressed.
